#!/bin/sh

########################################
# Preliminary data setup step
########################################

set -xa
# #### 06/25/2003 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

####################################
#
# obtain unique process id (pid) and make temp directories
#
####################################
echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo code_ver is ${code_ver:?} #ensure code_ver is defined
export pid=$$
export cycle=t${cyc}z

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  #NCO
  export BASEDIR=/tmpnwprd
else
  #developer
  export BASEDIR=/lfs/h2/emc/ptmp/wx21rg/
fi

export DATA=$BASEDIR/${job}.${pid}
mkdir -p $DATA
cd $DATA
export TMPDIR=$DATA

####################################
# File To Log Msgs
####################################
if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  #NCO
  if [ "$envir" = 'prod' ] ; then
    export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.$$
  else
    export jlogfile=/com/logs/${envir}/jlogfile
  fi
else
  #developer
  export jlogfile=~/jlogfile
fi


####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# variables that control processing
# Determine variable settings before testing and set them accordingly
#    SENDDBN=YES        file will be sent to OSO
#    SENDCOM=YES        copy files from TMPDIR to $COMOUT
#    SENDECF=YES        Flag Events on ECF
####################################
export SENDCOM=YES
export SENDECF=YES

if [ "$envir" = "prod" ] ; then
  export SENDDBN=YES
  export SENDDBN_GB2=YES
  export SENDDBN_SUFFIX=
else
  if [ $envir = "para" ] ; then
    export SENDDBN=YES
    export SENDDBN_GB2=YES
    export SENDDBN_SUFFIX=_PARA
  else
    export SENDDBN=NO
    export SENDDBN_GB2=NO
    export SENDDBN_SUFFIX=_TEST
  fi
fi

export NET=mmab
export RUN=seaice_drift

#################################################
# Specify job's execution areas (directory paths)
#################################################

#Path to home directory:
if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  #NCO
  export HOMEbase=/nw${envir}
else
  #dev
  export HOMEbase=$HOME/rgdev
fi

export HOMEsice=$HOMEbase/seaice_drift.${code_ver}
export EXECsice=$HOMEsice/exec
#export FIXsice=$HOMEsice/bigfix
export FIXsice=$HOMEsice/fix
export PARMsice=$HOMEsice/parm
export USHsice=$HOMEsice/ush

###################################
# Set up the UTILITIES
###################################
#Requires prod_util module to be established
export utilscript=$UTILROOT/ush
export utilexec=$UTILROOT/exec
export utilparm=$UTILROOT/parm 

##############################
# Run setup to initialize working directory and utility scripts
##############################
#sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
#export PDY=20121022
sh $utilscript/setpdy.sh
. ./PDY

##############################################
# Define COM directories
##############################################
if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  export COMbase=${COMROOTp2}/${NET}/${envir}
  export pcom=/pcom/$RUN
  #export COMIN=/com2/gens/prod/gefs.$PDY/$cyc/pgrb2a_bc
  #export COMINice_analy=/com2/omb/prod/sice.${PDYm1}
  #export COMIN=/gpfs/hps/nco/ops/com/naefs/prod/gefs.$PDY/$cyc/pgrb2a_bc
  export COMIN=${COMROOThps}/naefs/prod/gfs.${PDY}
  export COMINice_analy=`compath.py -e prod /seaice_analysis/v4.5.0/sice.${PDYm1}`
else
  export COMbase=$HOME/noscrub/com/${NET}/${envir}/
  export pcom=$HOME/noscrub/pcom/$RUN/

  export COMINice_analy=`compath.py -e prod /seaice_analysis/v4.5.0/seaice_analysis.${PDYm1}`
  #export COMINice_analy=$HOME/rgdev/drift/bigfix/
  echo zzz COMINice_analy $COMINice_analy

  # For hindcast thinned runs
  # export COMIN=$HOME/noscrub/gefs/
  # For NRT runs
  #   look under $COMROOT if needed
  export COMIN=${COMIN:-$(compath.py -e prod /naefs/v6.1/gefs.${PDY}/$cyc/pgrb2ap5_bc)}
  echo zzz COMIN = $COMIN

  export PYTHONPATH=$PYTHONPATH:$HOME/rgdev/ice_scoring/sidfex/:$HOME/rgdev/mmablib/py/
fi

if [ ! -d $COMIN ] ; then
  echo Could not find the input directory $COMIN exiting
  exit 1
fi
export COMOUT=$COMbase/${RUN}.${PDY}${cyc}
export COMOUT_sidfex=$COMbase/sidfex

mkdir -m 775 -p $COMOUT
mkdir -m 775 -p $COMOUT_sidfex
mkdir -m 775 -p $pcom

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

##############################################
# Execute the script
set -e
sh $HOMEsice/scripts/exseaice_drift.sh.ecf
export err=$?
err_chk
##############################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
date

cd $BASEDIR
##############################################
# Remove temp directories
##############################################
if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi
